server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/spirits?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password:

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
      format_sql: true
      show_sql: true
    open-in-view: true
app:
  imageFilePath: C:\Users\INSEONG\Desktop\국비지원 풀스택\팀프로젝트\주류추천서비스\제품 이미지